### ISSUE TITLE
Can't Reopen Detail Panel for Same Place Immediately after Closing It

### ISSUE THREAD

**Issue by nheick** [Esri/storymap-shortlist#76]
If you close the detail panel for a given place, you cannot reopen it immediately by selecting its tile again or by clicking on its point on the map.

This appears to be associated with the following code in DetailPanel.showDetails:

```
_swipers[themeIndex].on('onSlideChangeEnd', function () {
        $(currentDetailContainer).show();
	$(currentDetailContainer).css('z-index', 99);
});
```

Since the slide hasn't actually changed, but instead the detail container has been hidden, I think the onSlideChangeEnd event doesn't occur until you click on a different place.  Also, everytime the showDetails method is called, a new event handler gets registered.  If you add a console.log call in this function, it will print out once for every time showDetails has been called in the past.  If you keep clicking on the tile you just closed over and over because it won't open, when you finally click a different tile that does open, numerous event handlers fire off and you get many console statements at once.  This doesn't seem right.

**Comment by RupertEssinger** [comment]
This is fixed now in the release
