### ISSUE TITLE
show locate button in iframe (or add configurable option to do so)

### ISSUE THREAD

**Issue by TFimpel** [Esri/storymap-shortlist#79]
[Based on this page](https://geonet.esri.com/thread/189030-cant-display-locate-button-on-story-map-tour) I understand that the storymaps team has made the descision to not show a locate button if the storymap is used within an iframe. I think that is a real limitation for a lot of organizations who are required to put storymaps into websites that are created with the organization-specific web content management system that dictate things like headers, footers, etc... . IMHO it would be good to give storymap administrators an option to show the locate button even if it is loaded in an iframe.

**Comment by TFimpel** [comment]
In v2.2.3 all I had to do is go into viewer-min.js and change the test **window.top !== window.self** . This hack seems to not work anymore in v2.3.2 . That's unfortunate. If you could tell me how to make the locate button show up in an iframe with v.2.3.2 I'd appreciate that. Thanks.

**Comment by cooney** [comment]
We will not provide that option with the hosted apps, but that feature can be implemented by downloading the source code, making modifications, and hosting it on a server.
