### ISSUE TITLE
proxy rules for shortlist?

### ISSUE THREAD

**Issue by upcamogie** [Esri/storymap-shortlist#82]
I have a map tour app that works fine with the proxy rules that were given to me by suppoert and assistance in other template Githubs, so thanks. But now I am trying to replicate for the shortlist and am coming up, well, short.

My map and app are not shared so I want to use the proxy. I've added these lines in my index.html
//PROXY FOR SECURE AND NON SHARED CONTENT
							require(["esri/urlUtils"], function(urlUtils) {

							urlUtils.addProxyRule({
							urlPrefix: "https://www.arcgis.com/sharing/content",
							proxyUrl: "https://gis.mwcog.org/DotNet/proxy.ashx"
							});

							urlUtils.addProxyRule({
							urlPrefix: "https://gis.mwcog.org/wa/rest/services",
							proxyUrl: "https://gis.mwcog.org/DotNet/proxy.ashx"
							});
							});		
Tried adding it in a <script> tag at the end of my file

also added my proxy URL in the config.js
DEFAULT_PROXY_URL: "//my.org/DotNet/proxy.ashx"

what is different about this app template? I still get the log in for credentials. Support has  not been able to figure it out. I still hope one day to not have to do this each time I want to create an app. thanks.

**Comment by cooney** [comment]
Hi @upcamogie, it looks like its a bug on our side, we missed adding the PROXY_RULES parameter to the app config.  If you do so with: 
```// Optional array of proxy rules
	PROXY_RULES: [
		/*{
			urlPrefix: "http://services.arcgis.com/",
			proxyUrl: "http://myserver.domain.com/DotNet/proxy.ash"
		}*/
	],
```
to the config.js file (https://github.com/Esri/storymap-shortlist/blob/master/src/app/config.js#L104), all should work as expected.  

Also, try adding your addProxyRule code in the custom-scripts.js file instead of the index.html (https://github.com/Esri/storymap-series/blob/master/src/app/custom-scripts.js).  

Sorry for the confusion and frustration caused by this bug, and please let me know if you run into anything else.

**Comment by upcamogie** [comment]
Thanks @cooney  for the response and missing code. I added the PROXY_RULES to config.js and tried adding other proxy rules to the custom_scripts.js but have no luck. Tried also the index.html again and still receive the login , or nothing at all (when the code is in the custom .js. I think I have the syntax off somewhere-its likely something minor to someone who knows this stuff but but me unless I know where to put things exactly its quite a challenge

**Comment by cooney** [comment]
@upcamogie do you have a URL I could take a look at?  I might be able to guide you in the right direction

**Comment by upcamogie** [comment]
Thanks- I am testing my app here https://gis.mwcog.org/webmaps/tpb/lrp/

**Comment by cooney** [comment]
Try again to move the proxyRule code to the custom-scripts.js with: 
```
define(["dojo/topic", "esri/urlUtils"], function(topic, urlUtils) {
    /*
    * Custom Javascript to be executed while the application is initializing goes here
    */

    urlUtils.addProxyRule({
        urlPrefix: "https://www.arcgis.com/sharing/content",
        proxyUrl: "https://gis.mwcog.org/DotNet/proxy.ashx"
    });

    urlUtils.addProxyRule({
        urlPrefix: "https://gis.mwcog.org/wa/rest/services",
        proxyUrl: "https://gis.mwcog.org/DotNet/proxy.ashx"
    });

    // The application is ready
    topic.subscribe("tpl-ready", function(){
        /*
	* Custom Javascript to be executed when the application is ready goes here
	*/
    });
});
```

**Comment by upcamogie** [comment]
Thanks @cooney - app just hangs now. I am finally on the support radar so maybe they can figure it out. I am just baffled why this code would not work as with all the other story map apps out there. from what i see in dev tools the app does not even see the references to the proxy (which I know works). I'd take any other suggestions you have and will report back here with any resolution

**Comment by upcamogie** [comment]
Update- support told me to put the code back into index.html....essentially the same thing I did the other day on my own and it works now--someone else looks at it its magically fixed (i'll take it!). They told me that the custom-script.js would not work because there is no reference to that file in my index.html-- should there be? I used the 'downloadable' version that is not the whole source because I thought that is what users like me could use (as with other templates). I am happy to put my code in the custom JS file but do not know how to have the reference to it in the index.html. Is this another oversight/bug like w/ the config.js missing code? thanks-

**Comment by cooney** [comment]
Hi @upcamogie, thanks for the additional info and updates.  Looks like the app is working properly now and loading with the proxy.  The custom-script.js file does get loaded with the app, the code for that is in the main-app.js file instead of the index.html.
