### ISSUE TITLE
Browsers can't load built project

### ISSUE THREAD

**Issue by scMarth** [Esri/storymap-shortlist#87]
When I try to open my project in a browser, it fails to load.

I have tried IE, Firefox, and Chrome.

When I open the console log in FireFox, I see some warnings and errors:

Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience. For more help http://xhr.spec.whatwg.org/ init.js:14:256

Error: xhrFailed init.js:11:13

Use of getAttributeNode() is deprecated. Use getAttribute() instead.
init.js:159:263

Anyone else running into this issue?

**Comment by scMarth** [comment]
I was able to build the project with my laptop, which uses an older version of npm.

when I do 'npm version' in the laptop:

npm: 5.51
node: 8.9.3

when I do 'npm version' on my computer:

npm: 3.10.10
node: 6.10.2

So it seems like the project can't build with the latest version of npm. Can anyone else build the project with the latest version of npm?

**Comment by cooney** [comment]
I am not seeing any issues with building with the latest npm and node.  It looks like the version on your computer is the older version, and what you have on the laptop is the more current version.

**Comment by scMarth** [comment]
Thanks for the reply, That's good to know. I had the versions mixed up on my post, I fixed them. Something must be wrong with my computer setup then.

**Comment by scMarth** [comment]
Just to be clear, are you using the latest Current or LTS version of Node? If possible can you post the output of "npm version" command?

**Comment by cooney** [comment]
I am using the LTS version, 8.9.4, and npm 5.6.0

**Comment by scMarth** [comment]
Hello, I finally figured out what was the issue with my computer. It because my command prompt was locked.
