### ISSUE TITLE
Clicking on detailPictureDiv in iOS doesn't advance to next slide

### ISSUE THREAD

**Issue by scMarth** [Esri/storymap-shortlist#90]
There is a piece of code in DetailPanel.js:

https://github.com/Esri/storymap-shortlist/blob/master/src/app/storymaps/tpl/ui/desktop/DetailPanel.js

on line 504 that defines an click event for the detailPictureDiv. When the user clicks on the image, it advances to the next slide. When I test the storymap-shortlist in Chrome DevTools' Device Mode and choose an iOS device, it seems that this click function never fires.

It works fine when I test it on non-iOS devices though. I only have Android devices available, so I'm unable to test it on a real iOS device.

**Comment by RupertEssinger** [comment]
Hi @scMarth This is by design. We found in Shortlist on iOS that just swiping down to scroll down on the panel that shows the picture and text, was triggering an advance to the next point if the swipe touch point began on the image. So users were often unexpectedly advancing when they just meant to scroll down. So did a modification to remove that shortcut.

**Comment by scMarth** [comment]
Thanks for the reply @RupertEssinger. That makes sense. Is there a way for me to re-enable it? I'm working on a feature that shows a popup of an enlarged version of the image when the user taps the image.

**Comment by RupertEssinger** [comment]
@scMarth Let us know if your change makes it work like you want. Test to make sure that swiping down on the image doesn't invoke the popup you want to implement.

**Comment by scMarth** [comment]
@RupertEssinger Just an update: When I test in an emulated iOS device in Chrome DevTools, my changes work the way I want and swiping down from a picture doesn't invoke the popup. I don't have a real iOS device to test it in, as I only have an Android device, though.
